# alias|github_repo|holder_dir
wc|galateatech/waste-coordinator|/usr/local/code/active/galatea/waste-coordinator-holder
wcm|galateatech/waste-coordinator-mobile|/usr/local/code/active/galatea/waste-coordinator-mobile-holder
gi|galateatech/galatea-infrastructure|/usr/local/code/active/galatea/galatea-infrastructure-holder
pg|sferioncorp/planglobal|/usr/local/code/active/planglobal/planglobal-holder
pgi|sferioncorp/planglobalinc|/usr/local/code/active/planglobal/planglobal-inc-holder
sdc|sferioncorp/sferiondotcom|/usr/local/code/active/sferion/sferiondotcom-holder
sfc|sferioncorp/sferioncorporation|/usr/local/code/active/sferion/sferioncorporation-holder
epic|sferioncorp/epic|/usr/local/code/active/sferion/epic-holder
lfn|sferioncorp/liardfirstnation|/usr/local/code/active/sferion/liardfirstnation-holder
leeg|sferioncorp/leeg|/usr/local/code/active/leeg/leeg-holder
yolo|benstpierre/yolo|/usr/local/code/yolo-holder
