# alias|github_repo|holder_dir
wc|galateatech/waste-coordinator|/usr/local/code/sferion/galatea/waste-coordinator-holder
pg|sferioncorp/planglobal|/usr/local/code/sferion/planglobal/planglobal-holder
yolo|benstpierre/yolo|/usr/local/code/claude-native/yolo-holder
sdc|sferioncorp/sferiondotcom|/usr/local/code/sferion/sferiondotcom/sferiondotcom-holder
pgi|sferioncorp/planglobalinc|/usr/local/code/claude-native/planglobal-inc-holder
sfc|sferioncorp/sferioncorporation|/usr/local/code/sferion/sferioncorporation/sferioncorporation-holder
